# based on https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.pre-commit-config.yaml
default_language_version:
  python: python3.8

#ci: TODO(tilo): what is this good for?
#  autofix_prs: true
#  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
#  autoupdate_schedule: quarterly
#  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
#      - id: no-commit-to-branch
#        args: [ --branch, master, --branch, develop ]
      - id: check-ast
      - id: check-json
      - id: pretty-format-json
        args: [ --autofix ]
      - id: check-xml
      - id: check-symlinks
      - id: check-merge-conflict
#      - id: name-tests-test
#        args: [ '--django' ]        # uncomment to change tests to 'test_*.py' rather '*_test.py'
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: check-yaml
#      - id: check-docstring-first # tilo: don't care about doc-strings!
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=350', '--enforce-all']
        exclude: |
            (?x)^(
                path/to/big/file/that/should/be/allowed/to/commit/example.jpg|
                path/to/big/file/that/should/be/allowed/to/commit/another_example.jpg
            )$
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
        name: Upgrade code

#  - repo: https://github.com/PyCQA/isort
#    rev: 5.9.2
#    hooks:
#      - id: isort
#        name: Format imports

# flask (https://github.com/pallets/flask/blob/main/.pre-commit-config.yaml) uses:
# https://github.com/asottile/reorder_python_imports :   "Tool for automatically reordering python imports. Similar to isort but uses static analysis more."
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
#        files: "^(?!examples/)"
#        args: ["--application-directories", "src"]

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: Format code

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        args: [ --line-length=120 ]
        additional_dependencies: [ black==21.7b0 ]

  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: 'v1.5.7'  # Use the sha / tag you want to point at
      hooks:
      -   id: autopep8

  - repo: https://github.com/pycqa/pylint
    rev: v2.9.5
    hooks:
    -   id: pylint

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Check PEP8
        args:
          - "--config=setup.cfg"
        additional_dependencies: # see: https://github.com/pallets/flask/blob/main/.pre-commit-config.yaml
          - flake8-bugbear
          - flake8-implicit-str-concat

  -   repo: https://github.com/ikamensh/flynt/
      rev: '0.63'
      hooks:
      -   id: flynt
